all:
  hosts:
    192.168.57.17:
      ansible_connection: local
#
#  children:
#    # middleware
#    redis:
#      hosts:
#        192.168.57.18:
#        192.168.57.19:
#        192.168.57.20:
#    mysql:
#      hosts:
#        192.168.57.18:
#        192.168.57.19:
#
#    # application
#    application:
#      hosts:
#        192.168.57.18:
#
#    # monitor
#    monitor:
#      hosts:
#        192.168.57.20:
