# You SHOULD NOT implements vagrant specific tasks as roles.
# Because, if they are roles, they are be able to execute from site.yml, and it seems risk.
- name: "Vagrant Specific Tasks"
  hosts: all
  
  tasks:
    # zsh
    - name: "Install and Setup zsh"
      tags:
        - zsh
  
      block:
        - name: "Install zsh"
          become: yes
          package:
            name:
              - zsh
    
        - name: "Install zplug"
          git:
            repo: https://github.com/zplug/zplug
            dest: "/home/{{ system_user }}/.zplug"
  
    # anyenv
    - name: "Install anyenv"
      debug:
  
    # dotfiles
    - name: "Install and Setup My dotfiles"
      tags:
        - dotfiles
  
      block:
        - name: "Install stow"
          become: true
          package:
            name:
              - stow
          tags:
            - configuration
    
        - name: "Check ~/dotfiles/ exists"
          stat:
            path: "/home/{{ system_user }}/dotfiles"
          register: dotfiles_directory
    
        - name: "Stow dotfiles"
          shell: |
            cd /home/{{ system_user }}/dotfiles
            stow -R */
          when:
            - dotfiles_directory.stat.exists
            - dotfiles_directory.stat.readable

    # to build php
    # https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/install-from-source.yml
    - name: Ensure dependencies for building from source are installed (RedHat).
      become: true
      package:
        name: "{{ item }}"
      with_items:
        - autoconf
        - automake
        - libtool
        - bison
        - make
        - curl-devel
        - recode-devel
        - aspell-devel
        - libxml2-devel
        - pkgconfig
        - libmcrypt-devel
        - t1lib-devel
        - libXpm-devel
        - libpng-devel
        - libjpeg-turbo-devel
        - bzip2-devel
        - openssl-devel
        - freetype-devel
        - libicu-devel
        - mariadb-devel
        - gmp-devel
      when: ansible_os_family == 'RedHat'
    
    - name: Update apt cache (Debian).
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400
      when: ansible_os_family == 'Debian'
    
    - name: Ensure dependencies for building from source are installed (Debian).
      become: true
      apt:
        pkg: "{{ item }}"
      with_items:
        - build-essential
        - autoconf
        - automake
        - libtool
        - bison
        - pkg-config
        - re2c
        - libxml2-dev
        - libcurl4-openssl-dev
        - libbz2-dev
        - libjpeg-dev
        - libpng-dev
        - libxpm-dev
        - libfreetype6-dev
        - libgmp3-dev
        - libmcrypt-dev
        - libmysqlclient-dev
        - libpspell-dev
        - librecode-dev
        - libssl-dev
      when: ansible_os_family == 'Debian'
