- name: "Bootstrapping and System Configuration"
  hosts: all
  become: true

  # system wide
  roles:
    - role: user
      tags:
        - bootstrapping

    - role: geerlingguy.docker
      docker_users:
        -  "{{ system_user }}"
        -  "{{ application_user }}"
      docker_compose_version: "1.22.0"
      tags:
        - configuration
    
    - role: common
      tags:
        - configuration
