- import_playbook: site.yml

# You SHOULD NOT implements vagrant specific tasks as roles.
# Because, if they are roles, they are be able to execute from site.yml, and it seems risk.
- name: "Vagrant Specific Tasks"
  hosts: all

  tasks:
    # zsh
    - name: "Install and Setup zsh"
      tags:
        - zsh
  
      block:
        - name: "Install zsh"
          become: yes
          package:
            name:
              - zsh
    
        - name: "Install zplug"
          git:
            repo: https://github.com/zplug/zplug
            dest: "/home/{{ system_user }}/.zplug"
  
    # anyenv
    - name: "Install anyenv"
      debug:
  
    # dotfiles
    - name: "Install and Setup My dotfiles"
      tags:
        - dotfiles
  
      block:
        - name: "Install stow"
          become: true
          package:
            name:
              - stow
          tags:
            - configuration
    
        - name: "Check ~/dotfiles/ exists"
          stat:
            path: "/home/{{ system_user }}/dotfiles"
          register: dotfiles_directory
    
        - name: "Stow dotfiles"
          shell: |
            cd /home/{{ system_user }}/dotfiles
            stow -R */
          when:
            - dotfiles_directory.stat.exists
            - dotfiles_directory.stat.readable
