all:
  hosts:
    127.0.0.1:
      ansible_connection: local

  children:
    # middleware
    redis:
      hosts:
        127.0.0.1:
          ansible_connection: local
    mysql:
      hosts:
        127.0.0.1:
          ansible_connection: local

    # application
    application:
      hosts:
        127.0.0.1:
          ansible_connection: local
