all:
  hosts:
    localhost:
      ansible_connection: local

  children:
    # middleware
    redis:
      hosts:
        localhost:
          ansible_connection: local
    mysql:
      hosts:
        localhost:
          ansible_connection: local

    # application
    application:
      hosts:
        localhost:
          ansible_connection: local

    # work station
    work:
      hosts:
        localhost:
          ansible_connection: local
