name: Node.js Build and Test

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    name: npm cit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["latest"]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm cit
