name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
        with:
          registry-url: https://npm.pkg.github.com/
          scope: "@ndxbn"
      - run: npm ci
      - run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
